// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1HCUG69yY49z1f4kiZio7SmxXRQjZrso',
    appId: '1:362560717441:web:16a6c89ae849151d4e4380',
    messagingSenderId: '362560717441',
    projectId: 'flutterauth-6631d',
    authDomain: 'flutterauth-6631d.firebaseapp.com',
    storageBucket: 'flutterauth-6631d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH9V_SyYN1B2aKzsg5rNMFPC8U1fAmFuY',
    appId: '1:362560717441:android:4ee7949cfda572884e4380',
    messagingSenderId: '362560717441',
    projectId: 'flutterauth-6631d',
    storageBucket: 'flutterauth-6631d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmNc_MoyLfrWGsyIToNs5f1wRuJ5F4CT0',
    appId: '1:362560717441:ios:b41fb10cca77b35a4e4380',
    messagingSenderId: '362560717441',
    projectId: 'flutterauth-6631d',
    storageBucket: 'flutterauth-6631d.firebasestorage.app',
    iosBundleId: 'com.example.mytravel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmNc_MoyLfrWGsyIToNs5f1wRuJ5F4CT0',
    appId: '1:362560717441:ios:b41fb10cca77b35a4e4380',
    messagingSenderId: '362560717441',
    projectId: 'flutterauth-6631d',
    storageBucket: 'flutterauth-6631d.firebasestorage.app',
    iosBundleId: 'com.example.mytravel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1HCUG69yY49z1f4kiZio7SmxXRQjZrso',
    appId: '1:362560717441:web:4b4b8cdc2526110f4e4380',
    messagingSenderId: '362560717441',
    projectId: 'flutterauth-6631d',
    authDomain: 'flutterauth-6631d.firebaseapp.com',
    storageBucket: 'flutterauth-6631d.firebasestorage.app',
  );
}
